#!/bin/sh

. /home/ubuntu/magento/magento-1.9.1.0-1-64-bit/scripts/setenv.sh

exec /home/ubuntu/magento/magento-1.9.1.0-1-64-bit/php/sbin/.php-fpm.bin -y /home/ubuntu/magento/magento-1.9.1.0-1-64-bit/php/etc/php-fpm.conf -p /home/ubuntu/magento/magento-1.9.1.0-1-64-bit/php/var/ -c /home/ubuntu/magento/magento-1.9.1.0-1-64-bit/php/etc/php.ini "$@"
