#!/bin/sh

. /home/ubuntu/magento/magento-1.9.1.0-1-64-bit/scripts/setenv.sh
SASL_PATH="/home/ubuntu/magento/magento-1.9.1.0-1-64-bit/common/lib/sasl2"
            export SASL_PATH
exec /home/ubuntu/magento/magento-1.9.1.0-1-64-bit/common/sbin/.saslpasswd2.bin -f "/home/ubuntu/magento/magento-1.9.1.0-1-64-bit/common/etc/sasldb2" "$@"
